config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  devise_for :librarians, path: 'librarian', path_names: {sign_in: 'login',   sign_out: 'logout', password: 'senha'}
  devise_for :users, path: 'user', path_names: {sign_in: 'login',   sign_out: 'logout', password: 'senha'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books do
    get 'search', action: 'search', on: :collection
  end

  resources :users, only: [] do
    get 'make-favorite/:book_id', action: 'make_favorite', on: :collection, as: :make_a_book_favorite
    get 'favorites', action: 'favorites', on: :collection
  end

  namespace :librarians do
    resources :dashboard
    resources :books do
      get 'search', action: 'search', on: :collection
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, length: { in: 2..40  }

  def to_s
    name
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :title, presence: true
  validates :author_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  has_many :favorite_books
  has_many :users, through: :favorite_books
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validate :book_user_combination_uniqueness


  def book_user_combination_uniqueness
    if FavoriteBook.where(book_id: book_id, user_id: user_id).present?
      errors.add(:book_id, "Book and user combination already used")
    end
  end
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..40  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..40  }
  has_many :favorite_books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'users'
  protect_from_forgery except: :search

  def index
    @books = Book.order(:title).page(params[:page]).per(12)
    @authors = Author.all
  end

  def search
    term_criteria = params[:search][:term].present? ? "%#{params[:search][:term]}%" : nil
    author_criteria = params[:search][:author]
    order = params[:search][:order] || "asc"
    if author_criteria.present? && term_criteria.present?
      @books = Book.where('author_id = ? AND (title ilike ? or description ilike ?)',author_criteria, term_criteria, term_criteria).order(title: order).page(params[:page]).per(12)
    elsif term_criteria.present?
      @books = Book.where('title ilike ? or description ilike ?', term_criteria, term_criteria).order(title: order).page(params[:page]).per(12)
    else
      @books = Book.where(author_id: author_criteria).order(title: order).page(params[:page]).per(12)
    end
    render 'search', format: :js
  end
  
end

app/controllers/librarians/books_controller.rb
class Librarians::BooksController < LibrariansController

  before_action :book, only: [ :edit, :update]
  
  def book
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all.page(params[:page]).per(5)
  end

  def new
    @authors = Author.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book successfuly created!"
      redirect_to [:librarians, :books]
    else
      flash[:notice] = "There was a problem creating the book, please try again"
      render 'new'
    end
  end

  def edit
    @authors = Author.all
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "Book successfuly updated!"
      redirect_to [:librarians, :books]
    else
      flash[:notice] = "There was a problem updating the book, please try again"
      render 'edit'
    end
  end

  def book_params
    params.require(:book).permit(:title, :description, :author_id, :image)
  end
end

app/controllers/librarians/dashboard_controller.rb
class Librarians::DashboardController < LibrariansController
  
  def index

  end
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  layout 'librarians'
  before_action :authenticate_librarian!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'users'
  before_action :authenticate_user!
  
  def make_favorite
    book_id = params[:book_id]
    current_user.favorite_books.build(book_id: book_id)
    if current_user.save
      @user = current_user
      @favorites = @user.favorite_books.collect{|x| x.book}
      redirect_to [:favorites, :users]
    else
      @errors = "Não é possível favoritar o mesmo livro mais de uma vez."
      render 'error'
    end
  end

  def favorites
    books_ids = current_user.favorite_books.pluck(:book_id)
    @favorites = Book.where(id: books_ids).page(params[:page]).per(12)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_books.html.slim
.row
  - @books.each do |book|
    .col
      .card style=("width: 18rem;height: 284px;") 
        .card-body
          h5.card-title= book.title
          img(src="#{book.image}" style="max-width: 50px;max-height: 50px;")
          p.card-text= truncate(book.description, length: 80)
          p.card-text= book.author
          = link_to "Favorite", make_a_book_favorite_users_path(book), class: "btn btn-success"

= paginate @books

app/views/books/index.html.slim
h2 books
.row 
  .col 
    = simple_form_for :search, url: [:search, :books], html: {class: "form-search"}, method: :get, remote: true do |f|
      .row
        .col-4= f.input :term, input_html: { class: "form-control" }, label: "Search term", as: 'search', placeholder: 'Search Book'
        .col-4= f.input :author, collection: @authors, input_html: { class: "form-control" }, include_blank: false
        .col-4= f.input :order, collection: ["asc", "desc"], input_html:{class: "form-select"}, include_blank: false
        .col-4= f.submit "Search"

.result-set= render 'books'
  

app/views/books/search.js.erb
$('.result-set').html("<%= j render(partial: 'books') %>")

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title VirtualLibrary
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  body
    .container= yield

app/views/layouts/librarians.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title VirtualLibrary
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  body
    .container
      ul.nav
        li.nav-item
          a.nav-link.disabled  Authors
        li.nav-item= link_to 'Books', [:librarians, :books], class: "nav-link"
        li.nav-item
          a.nav-link.disabled  Users
        li.nav-item= button_to 'Logout', [:destroy, :librarian, :session], class: "nav-link", style: "border: none;background-color: white;", method: 'delete'
        
      = yield

app/views/layouts/users.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title VirtualLibrary
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  body
    .container
      -if current_user.present?
        ul.nav
          li.nav-item=link_to 'Home', [:root], class: "nav-link", style: "border: none;background-color: white;"
          li.nav-item
          li.nav-item=link_to 'Favorites', [:favorites, :users], class: "nav-link", style: "border: none;background-color: white;"
          li.nav-item= button_to 'Logout', [:destroy, :user, :session], class: "nav-link", style: "border: none;background-color: white;", method: 'delete'
      - else 
        ul.nav
          li.nav-item= button_to 'Login', [:new, :user, :session], class: "nav-link", style: "border: none;background-color: white;"
        
      = yield

app/views/librarians/books/_books.html.slim
table.table
  thead
    tr
      th scope="col"  #
      th scope="col"  Title
      th scope="col"  Author
      th scope="col"  Edit
  tbody
    - @books.each_with_index do |book, index|
      tr
        td= index + 1
        td= book.title
        td= book.author
        td= link_to "edit", [:edit, :librarians, book]

= paginate @books
    

app/views/librarians/books/_form.html.slim
= simple_form_for [:librarians, @book], html: { class: 'form-admin' } do |f|
  .form-group= f.input :title, input_html: {class: 'form-control'}
  .form-group= f.input :description, input_html: {class: 'form-control'}
  .form-group= f.input :image, placeholder: "informe a url da imagem", input_html: {class: 'form-control'}
  .form-group= f.input :author_id, collection: @authors, input_html: {class: 'form-control'}, include_blank: false
  = f.button :submit, class: "btn btn-success", data: {disable_with: "aguarde..."}

app/views/librarians/books/edit.html.slim
- content_for :head do
  title Virtual Library - Books

.section.mt-30.mb-30
  .container
    .row
      .col-12.col-sm-12
        .title-section
          h1 Edit Book

          ol.breadcrumb
            li.breadcrumb-item= link_to 'Dashboard', librarians_dashboard_index_path, title: 'Dashboard'
            li.breadcrumb-item= link_to 'Books', [:librarians, :books], title: 'Books'
            li.breadcrumb-item.active Edit Book

      .col-12.col-sm-8
        = render 'form'

app/views/librarians/books/index.html.slim
- content_for :head do
  title Virtual Library - Livros


.container
  .row
    .col-12.col-sm-12 
      h1 Livros
    .col-12.col-sm-4
      ol.breadcrumb
        li.breadcrumb-item= link_to 'Dashboard', librarians_dashboard_index_path, title: 'Dashboard'
        li.breadcrumb-item.active Books
      .title-section.section
        = link_to 'Novo Livro', [:new, :librarians, :book], class: 'btn btn-primary text-uppercase'
    .col-12.col-sm-8
      = simple_form_for :search, url: [:search, :librarians, :books], html: {class: "form-search"}, method: :get, remote: true do |f|
        .form-group
          = f.input :term, input_html: { class: "form-control" }, label: false, as: 'search', placeholder: 'Buscar livro'

    .col-12.col-sm-12
      .section
        = render "books"

app/views/librarians/books/new.html.slim
- content_for :head do
  title Virtual Library - Books

.section.mt-30.mb-30
  .container
    .row
      .col-12.col-sm-12
        .title-section
          h1 New Book

          ol.breadcrumb
            li.breadcrumb-item= link_to 'Dashboard', librarians_dashboard_index_path, title: 'Dashboard'
            li.breadcrumb-item= link_to 'Books', [:librarians, :books], title: 'Books'
            li.breadcrumb-item.active New Book

      .col-12.col-sm-8
        = render 'form'

app/views/librarians/dashboard/index.html.slim
h2 Dashboard

app/views/users/_books.html.slim
.row
  - @favorites.each do |book|
    .col
      .card style=("width: 18rem;height: 284px;") 
        .card-body
          h5.card-title= book.title
          img(src="#{book.image}" style="max-width: 50px;max-height: 50px;")
          p.card-text= truncate(book.description, length: 80)
          p.card-text= book.author

= paginate @favorites

app/views/users/error.html.slim
h2 favorites error
p= @errors

app/views/users/favorites.html.slim
h2 favorites
=render 'books'